import Head from "next/head";
import { Inter } from "@next/font/google";
import NavBar from "@/components/NavBar";
import PageTitle from "@/components/PageTitle";
import Media from "@/components/Media";
import Feed from "@/components/Feed";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  /* Tracks */
  /* const track1:TrackType = {id: 1, name: "song1", source: "/song1.mp3"}
  const track2:TrackType = {id: 2, name: "song2", source: "/song2.mp3"}

  const tracks:TrackType[] = [track1, track2] */

  const [feedIsHidden, setFeedIsHidden] = useState<boolean>(false);
  const [profileIsHidden, setProfileIsHidden] = useState<boolean>(true);
  const [cmtIsHidden, setCmtIsHidden] = useState<boolean>(true);

  const handleFeed = () => {
    setFeedIsHidden(false);
    setProfileIsHidden(true);
    setCmtIsHidden(true);
  };

  const handProfile = () => {
    setFeedIsHidden(true);
    setProfileIsHidden(false);
    setCmtIsHidden(true);
  };

  const handleCmt = () => {
    setFeedIsHidden(true);
    setProfileIsHidden(true);
    setCmtIsHidden(false);
  };

  return (
    <>
      <Head>
        <title>POLP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className="h-screen bg-cream">
        <NavBar />
        <PageTitle />
        {/* <div className="">
          <Feed />
        </div> */}
        <Media
          feedIsHidden={feedIsHidden}
          profileIsHidden={profileIsHidden}
          cmtIsHidden={cmtIsHidden}
        />
      </main>
    </>
  );
}
